=== galeone/XML-Parser/XML/AlbumFotografici/albumfotografici.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Lat" type="xs:integer" />
	<xs:element name="Long" type="xs:integer" />
	
	<xs:complexType name="luogoT">
		<xs:sequence>
			<xs:element name="Nome" type="xs:string" /> 
			<xs:element ref="Lat" />
			<xs:element ref="Long" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="fotoT">
		<xs:sequence>
			<xs:element name="Luogo" type="luogoT" />
			<xs:element name="Data" type="xs:date" /> 
			<xs:element name="Nome" type="xs:string" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="autoreT">
		<xs:sequence>
			<xs:element name="Nome" type="xs:string" />
			<xs:element name="Cognome" type="xs:string" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="albumFotograficoT">
		<xs:sequence>
			<xs:element name="Autore" type="autoreT" />
			<xs:element name="Nome" type="xs:string" />
			<xs:element name="Inizio" type="xs:date" />
			<xs:element name="Fine" type="xs:date" />
			<xs:element name="Foto" type="fotoT" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:element name="AlbumFotografico" type="albumFotograficoT" />
	
</xs:schema>

=== galeone/XML-Parser/XML/AlbumFotografici/sample.xml
<?xml version="1.0" encoding="UTF-8" ?>

<AlbumFotografico  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="albumfotografici.xsd">  
    
    <Autore>
    	<Nome>Carlo</Nome>
    	<Cognome>Giannelli</Cognome>
    </Autore>
    
    <Nome>Vacanze2011</Nome>
    
    <Inizio>2011-08-01</Inizio>
    
    <Fine>2011-08-31</Fine>
	
	<Foto>
		<Luogo>
			<Nome>Mare</Nome>
			<Lat>21</Lat>
			<Long>34</Long>
		</Luogo>
		<Data>2011-08-02</Data>
		<Nome>D123</Nome>
	</Foto>
	
	<Foto>
		<Luogo>
			<Nome>Bologna</Nome>
			<Lat>43</Lat>
			<Long>11</Long>
		</Luogo>
		<Data>2011-09-02</Data>
		<Nome>D126</Nome>
	</Foto>
	
	<Foto>
		<Luogo>
			<Nome>Mare</Nome>
			<Lat>21</Lat>
			<Long>34</Long>
		</Luogo>
		<Data>2011-08-07</Data>
		<Nome>D124</Nome>
	</Foto>
	
	<Foto>
		<Luogo>
			<Nome>Bologna</Nome>
			<Lat>43</Lat>
			<Long>11</Long>
		</Luogo>
		<Data>2011-07-31</Data>
		<Nome>D34126</Nome>
	</Foto>
	
</AlbumFotografico>
