=== galeone/XML-Parser/XML/Supermarket/merce.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	
	<xs:complexType name="prodottoT">
		<xs:sequence>
			<xs:element name="Nome" type="xs:string" />
			<xs:element name="Codice" type="xs:string" />
			<xs:element name="Prezzo" type="xs:positiveInteger" />
			<xs:element name="Giacenza" type="xs:positiveInteger" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="repartoT">
		<xs:sequence>
			<xs:element name="Nome" type="xs:string" />
			<xs:element name="Prodotto" type="prodottoT" minOccurs="0" maxOccurs="unbounded"/> 
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="supermercatoT">
		<xs:sequence>
			<xs:element name="Reparto" type="repartoT" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:element name="Supermercato" type="supermercatoT" />
	<xs:element name="Reparto" type="repartoT" />
	<xs:element name="Prodotto" type="prodottoT" />
	
</xs:schema>

=== galeone/XML-Parser/XML/Supermarket/sample.xml
<?xml version="1.0" encoding="UTF-8" ?>

<Supermercato  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="merce.xsd">  
    <Reparto>
    	<Nome>banane</Nome>
    	<Prodotto>
    		<Nome>buone</Nome>
    		<Codice>f124aa</Codice>
    		<Prezzo>33</Prezzo>
    		<Giacenza>12</Giacenza>
    	</Prodotto>
        <Prodotto>
    		<Nome>buone2</Nome>
    		<Codice>f424aa</Codice>
    		<Prezzo>3</Prezzo>
    		<Giacenza>121</Giacenza>
    	</Prodotto>
    	    <Prodotto>
    		<Nome>bu</Nome>
    		<Codice>f1a</Codice>
    		<Prezzo>22</Prezzo>
    		<Giacenza>124</Giacenza>
    	</Prodotto>
    </Reparto>
    
    <Reparto>
    	<Nome>testing</Nome>
    	<Prodotto>
    		<Nome>buone</Nome>
    		<Codice>f124aa</Codice>
    		<Prezzo>33</Prezzo>
    		<Giacenza>12</Giacenza>
    	</Prodotto>
    </Reparto>
    
</Supermercato>
